[package]
name = "golden-files"
version = "0.1.0"
edition = "2024"
authors = ["Clément Michaud"]
description = "Utility function to dump and read data into and from golden files."
license = "MIT"

[dependencies]
serde = "1.0"
serde_json = "1.0"
